name: Test & Detekt

on:

  pull_request:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable (for safety)
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Run Detekt
        run: ./gradlew detekt
